apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: custom-configuration
spec:
  replicas: 1
  service:
    type: LoadBalancer
    annotations:
       service.beta.kubernetes.io/aws-load-balancer-internal: "true"
       service.beta.kubernetes.io/aws-load-balancer-type: nlb
  persistence:
    storageClassName: rabbitmq-sc
  rabbitmq:
    additionalConfig: |
      log.console.level = debug
